// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TasksManagementApp.Infrastructure;

namespace TasksManagementApp.Migrations
{
    [DbContext(typeof(TasksManagementContext))]
    [Migration("20201224130513_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TasksManagementApp.Domain.TaskItems.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TaskId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCompleted = false,
                            Name = "Manage team tasks",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsCompleted = true,
                            Name = "Track progress",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsCompleted = false,
                            Name = "Buy product",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            IsCompleted = false,
                            Name = "Sell product",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsCompleted = false,
                            Name = "Manage transportation",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TasksManagementApp.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "baranauskas.aidas@gmail.com",
                            PasswordHash = "$2a$11$CzcOaxOxuZHcMO9tT5yueua9NZKe84.cNdUarlxq0LBh83B5Bb0zq",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "aidas.baranauskas@yahoo.com",
                            PasswordHash = "$2a$11$BhOFCvC6eHYPc9CSlUehmODG4WhPJTjVxqXJ/iAS3WYwkYZIilSNy",
                            Role = "user"
                        });
                });

            modelBuilder.Entity("TasksManagementApp.Domain.TaskItems.TaskItem", b =>
                {
                    b.HasOne("TasksManagementApp.Domain.Users.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
